SELECT table_name FROM information_schema.tables WHERE table_schema='public';

-- Criação de usuário para o banco de dados

CREATE USER abner WITH PASSWORD 'abner';

-- Criação das tabelas para a exeção das buscas em sql

CREATE TABLE public.aluno(
    numero bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
 	cpf bigint NOT NULL,
 	rg bigint NOT NULL,
 	nome character varying(255),
 	sexo character varying(9),
 	data_nascimento date,
 	email character varying(255),
 	telefones character varying(20),
 	endereço_atual character varying(300),
 	endereço_permanente character varying(300),
 	CONSTRAINT aluno_numero_pk PRIMARY KEY (cpf)
);

ALTER TABLE public.aluno OWNER to abner;

INSERT INTO public.aluno VALUES(1,11111111111,111111111,'Fulano de Tal','masculino','1998-04-12','fulano@gmail.com','+55 (12) 99999-4444', 'Rua dos Alfineiros','Rua dos Alfineiros')
INSERT INTO public.aluno VALUES(2,22222222222,222222222,'Donna Nobble','feminino','1983-05-10','donna@gmail.com','(12) 99223-2222', 'Rua Sete de Setembro, num 620, Alvorada','Rua dos Alfineiros');
INSERT INTO public.aluno VALUES(3,33333333333,333333333,'Martha Jones','feminino','1997-04-20','martha.jones@gmail.com','(12) 99999-3333', 'Rua Alfa, num 100, Centro','Rua Alfa, num 100, Centro');
INSERT INTO public.aluno VALUES(4,44444444444,444444444,'John Smith','masculino','1982-04-01','johnsimith@gmail.com','(12) 99999-2222', 'Rua Nelson Davila, num 150, Centro','Rua Nelson Davila, num 150, Centro');
INSERT INTO public.aluno VALUES(5,55555555555,555555555,'Peter Parker','masculino','1999-04-08','peter@gmail.com','(12) 99999-1111', 'Rua Lumem, num 140, Jd Apolo','Rua Lumem, num 140, Jd Apolo');

SELECT * FROM public.aluno;

CREATE TABLE public.professor(
    numero bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
 	cpf bigint NOT NULL,
 	nome character varying(255),
 	email character varying(255),
 	telefones character varying(20),
 	endereço character varying(300),
 	CONSTRAINT professor_cpf_pk PRIMARY KEY (cpf)
);

ALTER TABLE public.professor OWNER to abner;

INSERT INTO public.professor VALUES(1,11111111113,'Fulano de Tal','fulano@gmail.com','+55 (12) 99923-4444', 'Rua dos Alfineiros');
INSERT INTO public.professor VALUES(2,11111111112,'Dr. Otto Octavius','otto@gmail.com','+55 (12) 99932-4444', 'Rua Lumem, num 140, Jd Apolo');
INSERT INTO public.professor VALUES(4,11111111114,'Dr. Trevor Bruttenholm','professor.broom@gmail.com','+55 (12) 99912-4444', 'Rua Nelson Davila, num 120, Centro');

SELECT * FROM public.professor;
